### ISSUE TITLE
When I put dependency on kibana_lwrp cookbook in my metadata.rb I get following error

### ISSUE THREAD

**Issue by akulkarni-bk** [lusis/chef-kibana#100]
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/kibana_lwrp/libraries/install.rb
================================================================================

LoadError
---------
cannot load such file -- poise

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/kibana_lwrp/libraries/install.rb:10:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/kibana_lwrp/libraries/install.rb:

  3:  # Resource/Provider:: install
  4:  # Author:: John E. Vincent
  5:  # Author:: Paul Czarkowski
  6:  # License:: Apache 2.0
  7:  #
  8:  # Copyright 2014, John E. Vincent
  9:  
 10>> require 'poise'
 11:  
 12:  class Chef
 13:    class Resource::KibanaInstall < Resource
 14:      include Poise
 15:  
 16:      actions(:create, :remove)
 17:  
 18:      attribute(:name, kind_of: String, name_attribute: true)
 19:      attribute(:user, kind_of: String, default: 'kibana')

How do I include Poise in my chef setup? I tried to upload the cookbook but it complains that it does not have metadata.rb  in the master branch and kibana_lwrp does not specify a version I should stick to. Any help on this?

**Comment by spuder** [comment]
You need to resolve your dependencies. You could either

1. Clone the 'poise' cookbook to the same directory (You will need to make sure the folder name is the same as the cookbook name or you will get the error about the metadata)
2. Use berksshelf file and add poise to the dependency list. 

http://berkshelf.com/

**Comment by martinb3** [comment]
With no response for a few months, I'm going to consider this closed.
