### ISSUE TITLE
Document default_app_id requirement

### ISSUE THREAD

**Issue by davidski** [lusis/chef-kibana#111]
[This](https://github.com/lusis/chef-kibana/issues/new) recent change makes it required to pass `default_app_id` to the `kibana.yml` template. While the sample recipe has this parameter included, this requirement would be a nice thing to put in the `CHANGELOG`....or to have the template supply a default value if no parameter is passed in. ;)

**Comment by martinb3** [comment]
I agree :) We'll get this in there before a new version is released that includes the change. :+1: Thanks!
