### ISSUE TITLE
Bug in kibana_lwrp::install

### ISSUE THREAD

**Issue by Aditya-prit** [lusis/chef-kibana#116]
Chef::Exceptions::InvalidResourceSpecification
  ----------------------------------------------
  You must specify `resource_name'!

**Comment by martinb3** [comment]
Please tell us what version of Chef as well as what version of the cookbook you're using, as well as give us an example of how you're using it. Thank you!

**Comment by dthornton** [comment]
Hello,

FWIW, I was running into this same error while converging a basic install recipe on an older version of Chef (12.2.1) with the latest version of the kibana_lwrp cookbook (3.0.2).

After a few quick tests I found the error only occurs on Chef versions < 12.5.1. Newer versions >= 12.5.1 work fine. I am currently using the latest 12.11.18 without any issues.

Could possibly have something to do with the new custom resources that came in 12.5 but I'm not sure. https://docs.chef.io/release/12-5/release_notes.html

I will try to find more time to dig in and find the actual cause but I wanted to share this for now. Let me know if I can provide any additional info.

Thank you!

**Comment by martinb3** [comment]
Indeed, there were a huge number of changes to resources/providers across 12.3, 12.4, and 12.5. Some of which were not backwards compatible, so I think that's what you're seeing here. I'll open an issue to try to adopt https://github.com/chef-cookbooks/compat_resource, but ultimately, it appears that compatibility was broken across those bugfixes.
