### ISSUE TITLE
Implement chef-compat resources

### ISSUE THREAD

**Issue by martinb3** [lusis/chef-kibana#120]
Per issues like #116, implement https://github.com/chef-cookbooks/compat_resource to aid in backwards compatibility.

**Comment by martinb3** [comment]
I apparently did this months ago! Just merged https://github.com/lusis/chef-kibana/commit/dabf4430c5951f7596e820f1dec3e51a7d3528e7 into master.

**Comment by dthornton** [comment]
Awesome. Thank you!
