### ISSUE TITLE
Switch to chef_nginx cookbook

### ISSUE THREAD

**Issue by eherot** [lusis/chef-kibana#124]
The [miketheman/nginx](https://github.com/miketheman/nginx) cookbook is no longer being actively maintained (which causes problems because of things like the version constraint on `ohai ~> 2.0`). Consider switching to [chef-cookbooks/nginx](https://github.com/chef-cookbooks/chef_nginx) instead, which is being actively maintained by Chef.

**Comment by waltercool** [comment]
Is this project still maintained?

**Comment by martinb3** [comment]
Hi @waltercool -- I'd be happy to review + merge PRs. I haven't had any time to chip in code, but I'm glad to review/merge.

**Comment by waltercool** [comment]
Many thanks
