### ISSUE TITLE
Overriding the ["kibana"]["user"] attribute may fail convergence

### ISSUE THREAD

**Issue by doublerr** [lusis/chef-kibana#13]
Defaults work on systems that have `www-data` user but overriding the attribute will break if the user doesn't have a shell or doesn't exist. This is common when using a user like `apache` or `nginx`.

possible fix:

Remove the user from the various git/template commands and come in afterwards to change ownership of directories but only if the default user is not empty.

There is still an issue if the user doesn't exist at all but that may be outside this cookbook.

**Comment by martinb3** [comment]
I'm helping to close old issues here, and I believe `www-data` is no longer present in this cookbook, so this is probably something that can be closed as stale. Thanks for the initial report Ryan! :)
