### ISSUE TITLE
Consider Adding to the OpsCode Chef Repo

### ISSUE THREAD

**Issue by nappa32** [lusis/chef-kibana#18]
Would you add this to the Opcode repo ? I'm doing testing in Chef-Solo, and it's a lot easier to just add a line in metadata.rb file than to upload manually.

**Comment by spuder** [comment]
If you are using berkshelf (which you really should), then you can override where chef pulls the cookbook from like so:

Berkshelf

     coobook 'chef-kibana', git: 'https://github.com/lusis/chef-kibana.git'

**Comment by martinb3** [comment]
Since #61 was resolved, I think we can close this as well. Thanks all!
