### ISSUE TITLE
proxy pass

### ISSUE THREAD

**Issue by t5unamie** [lusis/chef-kibana#42]
Kibana3 changed it's request a few months ago. So if your checking out kibana3 master.

The following file

https://github.com/lusis/chef-kibana/blob/master/templates/default/kibana-nginx.conf.erb

needs to have the following changed from

location ~ ^/_aliases$ {
    proxy_pass <%= @es_scheme %><%= @es_server %>:<%= @es_port %>;
    proxy_read_timeout 90;
  }

To 

location ~ /_aliases$ {
    proxy_pass <%= @es_scheme %><%= @es_server %>:<%= @es_port %>;
    proxy_read_timeout 90;
  }

**Comment by martinb3** [comment]
I believe with Kibana 4, this is no longer an issue. I'm going to close, but please comment or re-open if it's still an issue. Thank you!
