### ISSUE TITLE
Documentation Confusion

### ISSUE THREAD

**Issue by rlangford** [lusis/chef-kibana#49]
The readme states:

node['kibana']['install_type'] - The type of install we are going to use either git or zipfile

while, the attributes file states:

default['kibana']['install_type'] = "git" # git | file

Is it 'zipfile', or is 'file' correct?

**Comment by martinb3** [comment]
This doesn't appear to be in the README.md any longer. Please advise if we should re-open this to address it elsewhere. Thank you!
