### ISSUE TITLE
Support for Kibana 4

### ISSUE THREAD

**Issue by davidski** [lusis/chef-kibana#84]
With Kibana 4 now entering RC stage, it's probably time to start thinking about updating this cookbook to handle the new infrastructure required for KB4. Opening this issue for tracking and having a discussion about how best to accomplish this support (keep support for KB 3? go all in on KB 4? create a separate cookbook?).

**Comment by BrianEWhipple** [comment]
+1 
4.0 has been released: http://www.elasticsearch.org/blog/kibana-4-literally/

**Comment by paulczar** [comment]
We've supported KB4 (beta) on master for a while now with KB3 support being branched off.

**Comment by BrianEWhipple** [comment]
The cookbook needs work to support the official 4.0 release from this past week.  Doesn't seem like much but unfortunately I don't have time right now to contribute a PR.  Might have time in a few weeks, but suspect others will want to start using official 4.0 release before then.

**Comment by paulczar** [comment]
I've added support for the official kibana 4 release.  there were a few minor tweaks to config settings that had changed.    release is 2.0.4 and has been uploaded to supermarket.

**Comment by BrianEWhipple** [comment]
Thanks for the quick turnaround.  2.0.4 is working for me.  Thanks!
