### ISSUE TITLE
Kibana 4.0.0-linux-x64 doesn't work

### ISSUE THREAD

**Issue by jeffreyji666** [lusis/chef-kibana#88]
When accessing the url: http://localhost:5601 after the chef installation of kibana 4.0.0-linux-x64, I got this error:

Uncaught ReferenceError: ZeroClipboard is not defined (http://localhost:5601/index.js?_b=5888.89881).

and I don't know why.

**Comment by paulczar** [comment]
are you still seeing this with the latest release?   I think that had something to do with the plugins specified in the config and I fixed it ... maybe?

**Comment by jeffreyji666** [comment]
yeah, I still have this problem, and I don't have any plugin.

**Comment by patcon** [comment]
+1

Getting the same thing. Moving on to using chef-elkstack though, which seems to have a setup with this cookbook that bypasses whatever the issue is

**Comment by martinb3** [comment]
Hello! This appears to have been a bug in their release, via https://github.com/elastic/kibana/issues/2617. It should be fixed in newer versions.
