### ISSUE TITLE
Pin back to poise ~> 1.x or make compatible with 2.x

### ISSUE THREAD

**Issue by martinb3** [lusis/chef-kibana#90]
Seeing some folks report issues with this cookbook, e.g. https://github.com/rackspace-cookbooks/elkstack/issues/149. These seem to boil down to recent changes to poise.

**Comment by ericachelis** [comment]
We just saw this issue too:
```
uninitialized constant Chef::Resource::KibanaInstall::Poise
```
We were able to temporarily resolve until the next release by locking poise version to 1.x in our metadata.rb:
```
depends 'poise', '= 1.0.12'
```

Thanks for the pointer and fix!
