### ISSUE TITLE
uninitialized constant Chef::Resource::KibanaInstall::Poise

### ISSUE THREAD

**Issue by pmarshall05** [lusis/chef-kibana#92]
I am getting the following error when converging on EC2:  `uninitialized constant Chef::Resource::KibanaInstall::Poise`

Any ideas on how to fix, outside of adding `require 'poise'` to the top of libraries/install.rb?

**Comment by pmarshall05** [comment]
Nevermind,  I answered my own question.

I pinned the poise cookbook in metadata.rb
`depends 'poise', '1.0.12'`

**Comment by EdHurtig** [comment]
Going to point to https://github.com/lusis/chef-kibana/pull/91 should fix this so that manual pinning is not required
