### ISSUE TITLE
cookbook wont run in AWS OPSWORKS chef 11.10 

### ISSUE THREAD

**Issue by arinba** [lusis/chef-kibana#97]
Hi 
When im trying to run that cookbook on my Opsworks stack using the latest available chef version 11.10 - poise makes problems :+1:  Halite is not compatible with no_lazy_load false, please set no_lazy_load true in your Chef configuration file
as poise is not nessesary for kibana per se and Opsworks still do not support chef 12 for linux stacks 
can a backward compatibility be added ?

**Comment by martinb3** [comment]
Chef 11.10 was released over 2 years ago. I think you'll have more luck pushing AWS to update.

**Comment by arinba** [comment]
:)
Yep you are right ...
any how - now AWS has their own implementation of Elastic stack ready made
- the only downside of this is that it will not use recent releases

Arin

Best Regards
Arin Ben Aharon
Co CEO &Founder
Cellular: 972-54-6662330
Algoma Systems LTD

**Comment by martinb3** [comment]
With Opsworks now supporting Chef 12 on Linux, I'm going to close this. I assume it's resolved. Thank you for the report!
